---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      chart: nextcloud
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  interval: 1m0s
  values:
    externalDatabase:
      database: nextcloud
      enabled: true
      existingSecret:
        enabled: true
        secretName: postgres
        usernameKey: db-username
        passwordKey: db-password
      host: "nextcloud-db.cu8h8rsvexrg.us-east-1.rds.amazonaws.com"
      type: postgresql

    ingress:
      annotations: {}
      enabled: false
      labels: {}
      path: /
      pathType: Prefix

    nextcloud:
      configs: {}
      containerPort: 80
      datadir: /var/www/html/data
      existingSecret:
        enabled: true
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
          # tokenKey: nextcloud-token
      host: nextcloud.kube.local
      password: admin
      persistence:
        subPath: null
      phpConfigs: {}
      podSecurityContext: {}
      securityContext: {}
      username: admin

    redis:
      enabled: true
      auth:
        enabled: true
        password: ""
        existingSecret: nextcloud-redis
        existingSecretPasswordKey: redis-password

      master:
        persistence:
          enabled: false
      masterService: nextcloud-redis-master
      replica:
        persistence:
          enabled: false
      replicaService: nextcloud-redis-replica
    replicaCount: 1

    service:
      loadBalancerIP: ""
      nodePort: nil
      port: 8080
      type: ClusterIP
