---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 1m0s
  type: oci
  # url: http://localhost:8080
  url: https://nextcloud.github.io/helm/
