---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 1m0s
  values:
    additionalArguments:
      - --certificatesresolvers.letsencrypt.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.httpChallenge.entryPoint=web
      - --certificatesresolvers.letsencrypt.acme.storage=/tmp/acme/acme.json
    ports:
      web:
        redirectTo: 
          port: websecure
      websecure:
        tls:
          enabled: true
          certResolver: letsencrypt
    securityContext:
      readOnlyRootFilesystem: false
    initContainers:
      - name: volume-permissions
        image: busybox:latest
        command: ["sh", "-c", "mkdir -p /tmp/acme && touch /tmp/acme/acme.json && chmod 600 /tmp/acme/acme.json"]
        securityContext:
          runAsUser: 0
